Algoritmo "Area do paralelogramo"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : cálculo automatizado da area de um hexágono
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
base: real
altura: real
resultado: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o valor da base do paralelogramo")
leia(base)
escreva("Digite o valor da altura do paralelogramo")
leia(altura)
resultado<- (base * altura)
escreva("O resultado da área do paralelogramo é:", resultado)

Fimalgoritmo