Algoritmo "Cálculo da área de um círculo "
// Disciplina   :[Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : cálculo área do círculo
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
raio: real
resultado: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Qual o valor do raio do círculo? ")
leia(raio)
resultado<- ((raio * raio) * 3.14)
escreva("O valor da área do círculo é:", resultado)


Fimalgoritmo