Algoritmo "Area do pentagono"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : cálculo automatizado da area de um pentágono
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis
lado: real
altura: real
resultado: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o valor do lado do pentágono")
leia(lado)
escreva("Digite o valor da altura do pentágono")
leia(altura)
resultado<- (lado * altura * 5)
// 5 pois, o pentágono possui 5 lados)
escreva("O resultado da área do pentágono é:", resultado)



Fimalgoritmo