Algoritmo "Cálculo da área de um retângulo "
// Disciplina   :[Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicite o nome do usuário e exiba o resultado
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
base: inteiro
altura: inteiro
resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor da base")
leia (base)
escreva("Digite o valor da altura")
leia(altura)
resultado <- (base * altura)
escreva("O resultado da área deste retângulo é:", resultado)

Fimalgoritmo