Algoritmo "Cronômetro"
// Disciplina   : [Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   :Cronômetro
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 14/04/2026
Var
   // Seção de Declarações das variáveis
   minutos: inteiro
   segundos: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Exemplo repetiçãocomo cronômetro")
   para minutos de 0 até 59 passo 1 faça
      para segundos de 1 até 59 passo 1  faça
      escreval(minutos, " :", segundos)
      fimpara
   fimpara

Fimalgoritmo