Algoritmo "Digite seu nome2"
// Disciplina   :[Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicite o nome do usuário e exiba o resultado
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis:
nome: caracter
sobrenome: caracter
nomecompleto: caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite seu nome:")
Leia(nome)
Escreva("Digite seu sobrenome:")
Leia(sobrenome)
Escreva("Seja bem vindo(a), ", nome , " ",sobrenome)
nomecompleto<- (nome+ " " +sobrenome)
Escreva("Seja bem vindo(a), ", nomecompleto)

Fimalgoritmo