Algoritmo "divisivel"
// Disciplina   :[Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Efetuar a leitura de quatro números inteiros e
//apresentar os números que são divisíveis por 2 e 3. .
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 05/04/2026
Var
// Seção de Declarações das variáveis
a: inteiro
b: inteiro
c: inteiro
d: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor de a:")
leia(a)
escreva("Digite o valor de b:")
leia(b)
escreva("Digite o valor de c:")
leia(c)
escreva("Digite o valor de d:")
leia(d)

se ( a mod 2 = 0) e (a mod 3 = 0) entao
escreval ("O número a é divisível por 2 e 3")
fimse


se (b mod 2 = 0) e (b mod 3 = 0) entao
escreval ("O número b é divisível por 2 e 3")
fimse

se (c mod 2 = 0) e (c mod 3 = 0) entao
escreval ("O número c é divisível por 2 e 3")
fimse

se (d mod 2 = 0) e (d mod 3 = 0) entao
escreval ("O número d é divisível por 2 e 3")
fimse




Fimalgoritmo