Algoritmo "Divisão"
// Disciplina   :[Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicite ao usuário dois números,
// dividir e exibir o resultado
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
numero1: real
numero2: real
resultado: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um número inteiro")
leia(numero1)
escreva("Digite um número inteiro")
leia(numero2)
resultado<- (numero1 / numero2)
escreva("A divisão entre os dois número é:", resultado)


Fimalgoritmo