Algoritmo "estrutura_de_repeticao"
// Disciplina   :[Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicite o valor que o usuário quer sacar, utilie o mod para
// entregar as cédulas correspondentes da maneira correta.
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 01/04/2026
Var
   // Seção de Declarações das variáveis
   conta: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto conta <5 faça
      escreval("Thiago é chato!")
      conta<- conta+1
      fimenquanto


Fimalgoritmo