Algoritmo "estrutura_de_decisao_encadeada"
// Disciplina   :[Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Demonstrar a estrutura de decisão encadeada
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 29/03/2026
Var
   // Seção de Declarações das variáveis
   numero1: inteiro




Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("digite um valor:")
   leia(numero1)
   se numero1 < 10 entao
      escreval ("O número digitado é menor que 10")
   senao
      se numero1=10  entao
         escreval ("O número digitado é igual a 10")
      senao
         escreval("O número digitado é maior que 10")
      fimse
   fimse
Fimalgoritmo