Algoritmo "fahrenheit_para_celsius"
// Disciplina   :[Lógica de Programação com VisualG]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicite a temperatura em fahrenheit e converta-a para Celsius
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 03/04/2026
Var
// Seção de Declarações das variáveis 
fahrenheit: real
resultado: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor da temperatura em fahrenheit:")
leia(fahrenheit)
resultado<- ((fahrenheit - 32) * (5/9))
escreva("O resultado da temperatura em Celsius é:", resultado)


Fimalgoritmo