Algoritmo "media aritmetica de tres valores "
// Disciplina   :[Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Leia três números e calcule a média aritmética.
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 29/03/2026
Var
// Seção de Declarações das variáveis 
valor1: real
valor2: real
valor3: real
resultado1: real
resultado2: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual o primeiro valor? ")
leia(valor1)
escreva("Qual o segundo valor? ")
leia(valor2)
escreva("Qual o terceiro valor? ")
leia(valor3)
resultado1<- (valor1 + valor2 + valor3)
resultado2<- (resultado1/3)
escreva("A média aritmética entre os três valores é:", resultado2)


Fimalgoritmo