Algoritmo "Perimetro do quadrado"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Leia o valor do lado de um quadrado e calcule o perímetro.
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 29/03/2026
Var
// Seção de Declarações das variáveis
lado: real
resultado: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o valor do lado do quadrado:")
leia(lado)
resultado<- (4 * lado)
escreva("O perímetro do quadrado é:",resultado)


Fimalgoritmo