Algoritmo "quadrado_do_numero_15_a_200"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 13/04/2026
Var
   // Seção de Declarações das variáveis
   contadora: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contadora <- 15
   repita
      escreval("O quadrado do número ", contadora, "é:", contadora * contadora)
      contadora<- contadora + 1
   ate contadora>200




Fimalgoritmo