Algoritmo "Subtração"
// Disciplina   :[Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicite ao usuário dois números inteiros,
//subtrair e exibir o resultado
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
 numero1: inteiro
 numero2: inteiro
 resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite um número inteiro")
 leia(numero1)
 escreva("Digite um número inteiro")
 leia(numero2)
 resultado<-(numero1 - numero2)
 escreva("A subtração entre os dois números digitados é:", resultado)


Fimalgoritmo