Algoritmo "valor produto "
// Disciplina   :[Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Leia o preço de um produto e a quantidade comprada. Calcule o valor total da compra.
// Autor(a)    : Beatriz Lacerda Rodrigues
// Data atual  : 29/03/2026
Var
// Seção de Declarações das variáveis 
valor: real
quantidade: real
resultado: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Qual a quantidade do produto que você comprou? ")
leia(quantidade)
escreva("Qual o valor deste produto? ")
leia(valor)
resultado<- (quantidade * valor)
escreva("O valor total da compra é de:", resultado)

Fimalgoritmo